# Use the official MySQL image
FROM mysql:8

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=food_ordering_db
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin123

# Copy the initialization script
COPY init.sql /docker-entrypoint-initdb.d/

# Expose MySQL port
EXPOSE 3306
